[marks]
nv = "$HOME/.config/${NVIM_APPNAME:-nvim}/lua"
zsh = "$HOME/.config/zsh"
ctx = "$CUSTOM_HOME"
home = "$HOME"
git = "$(git rev-parse --show-toplevel)"
dot = "$HOME/dotfiles"
conf = [
  "$XDG_CONFIG_HOME/alacritty"
  "$XDG_CONFIG_HOME/tmux"
  # "$XDG_CONFIG_HOME/hypr"
  # "$XDG_CONFIG_HOME/mako"
  # "$XDG_CONFIG_HOME/waybar"
]
